HEADER = "Exceptions"

SELECTBOX_TITLE = "Types"

FILE_PATH_PREFIX = "exception"

SELECTBOX_OPTION_TO_FILE_PATHS = {
    "Runtime Exception": "Runtime"
}

CONSTS_DICT = {
    "HEADER": HEADER,
    "SELECTBOX_TITLE": SELECTBOX_TITLE,
    "FILE_PATH_PREFIX": FILE_PATH_PREFIX,
    "SELECTBOX_OPTION_TO_FILE_PATHS": SELECTBOX_OPTION_TO_FILE_PATHS
}
