HEADER = "Git"

SELECTBOX_TITLE = "Commands"

FILE_PATH_PREFIX = "git"

SELECTBOX_OPTION_TO_FILE_PATHS = {
    "git branch": "Branch"
}

CONSTS_DICT = {
    "HEADER": HEADER,
    "SELECTBOX_TITLE": SELECTBOX_TITLE,
    "FILE_PATH_PREFIX": FILE_PATH_PREFIX,
    "SELECTBOX_OPTION_TO_FILE_PATHS": SELECTBOX_OPTION_TO_FILE_PATHS
}
