HEADER = "Keywords"

SELECTBOX_TITLE = "Languages"

FILE_PATH_PREFIX = "key"

SELECTBOX_OPTION_TO_FILE_PATHS = {
    "Java": "Java"
}

CONSTS_DICT = {
    "HEADER": HEADER,
    "SELECTBOX_TITLE": SELECTBOX_TITLE,
    "FILE_PATH_PREFIX": FILE_PATH_PREFIX,
    "SELECTBOX_OPTION_TO_FILE_PATHS": SELECTBOX_OPTION_TO_FILE_PATHS
}
