HEADER = "Redis"

SELECTBOX_TITLE = "Components"

FILE_PATH_PREFIX = "redis"

SELECTBOX_OPTION_TO_FILE_PATHS = {
    "Concepts": "Concepts"
}

CONSTS_DICT = {
    "HEADER": HEADER,
    "SELECTBOX_TITLE": SELECTBOX_TITLE,
    "FILE_PATH_PREFIX": FILE_PATH_PREFIX,
    "SELECTBOX_OPTION_TO_FILE_PATHS": SELECTBOX_OPTION_TO_FILE_PATHS
}
