HEADER = "SOA"

SELECTBOX_TITLE = "Components"

FILE_PATH_PREFIX = "soa"

SELECTBOX_OPTION_TO_FILE_PATHS = {
    "Concepts": "Concepts",
    "Development": "Dev",
    "Dubbo": "Dubbo"
}

CONSTS_DICT = {
    "HEADER": HEADER,
    "SELECTBOX_TITLE": SELECTBOX_TITLE,
    "FILE_PATH_PREFIX": FILE_PATH_PREFIX,
    "SELECTBOX_OPTION_TO_FILE_PATHS": SELECTBOX_OPTION_TO_FILE_PATHS
}
